# Generated by Django 4.0 on 2022-01-05 07:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_pass_forgot_alter_profile_pass_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('udid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('signature', models.ImageField(null=True, upload_to='')),
                ('export_quality', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=7)),
                ('Language', models.CharField(max_length=20)),
                ('user_stared_templates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('user_stared_backgrounds', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('user_stared_stickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('user_stared_Textart', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('user_stared_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('user_stared_fonts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('most_used_fonts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('user_custom_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('instagram_follower', models.BooleanField(default=False)),
                ('grid_snapping', models.BooleanField(default=False)),
                ('user_recent_text', models.CharField(max_length=255)),
                ('appearance_mode', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Auto', 'Auto')], max_length=7)),
                ('enable_iCloud_backup', models.BooleanField(default=False)),
                ('save_projects_automatically', models.BooleanField(default=False)),
                ('save_projects_on_export', models.BooleanField(default=False)),
                ('notifications_permission', models.BooleanField(default=False)),
                ('inApp_notifications_permission', models.BooleanField(default=False)),
                ('photo_library_permission', models.BooleanField(default=False)),
                ('digital_riyals_rewards', models.IntegerField()),
                ('enable_touch', models.BooleanField(default=False)),
                ('app_theme', models.CharField(choices=[('Option1', 'Optionb1'), ('Option2', 'Option2'), ('Option3', 'Option3')], max_length=7)),
                ('always_crop', models.BooleanField(default=False)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
