# Generated by Django 4.0 on 2022-01-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='user_detail',
        ),
    ]
