# Generated by Django 4.0 on 2022-01-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_details_user_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='app_theme',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3')], max_length=7),
        ),
    ]
