# Generated by Django 4.0 on 2022-01-10 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_detail_app_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_data',
            fields=[
                ('aid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('UID', models.CharField(max_length=200, unique=True)),
                ('inApp_Products', models.CharField(max_length=100)),
                ('Purchase_date', models.DateTimeField(blank=True, null=True)),
                ('Purchased_product', models.CharField(max_length=100)),
                ('Device_Model', models.CharField(max_length=50)),
                ('iOS', models.CharField(max_length=100)),
                ('Device_Storage', models.CharField(max_length=10)),
                ('Lunch_count', models.IntegerField()),
                ('Push_Notification_Status', models.BooleanField(default=False)),
                ('Library_permission_Status', models.BooleanField(default=False)),
                ('Latest_Geolocation', models.FloatField(max_length=30)),
                ('Carrier', models.CharField(max_length=100)),
                ('App_Last_Opened', models.DateTimeField()),
                ('Purchase_attempts', models.IntegerField()),
                ('Grace_Period', models.CharField(max_length=100)),
                ('Remaining_grace_period_days', models.IntegerField()),
                ('Number_of_projects', models.IntegerField()),
                ('Total_time_spent', models.DateTimeField()),
                ('total_ads_served', models.IntegerField()),
                ('Registered_user', models.BooleanField(default=False)),
                ('Push_Notification_token', models.BooleanField(default=False)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
