# Generated by Django 4.0 on 2022-01-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_application_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_data',
            name='Total_time_spent',
            field=models.CharField(max_length=10),
        ),
    ]
